/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import javax.persistence.*;
import java.util.Date;

/**
 * A review written by a user for a shoe. Stores the rating, comments, and date
 * of the review.
 */
@Entity
@Table(name = "REVIEW")
public class Review {

    /**
     * The unique ID of the review. Auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    private int id;

    /**
     * The shoe that is being reviewed. Each review is for one shoe.
     */
    @ManyToOne
    @JoinColumn(name = "ID_SHOE", nullable = false)
    private Shoe shoe;

    /**
     * The user who wrote this review. Can be saved with the review.
     */
    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @JoinColumn(name = "USERNAME")
    private User user;

    /**
     * The text comment of the review. Maximum 40 characters.
     */
    @Column(name = "DESCRIPTION", length = 40)
    private String description;

    /**
     * The star rating (1-5). This is required for every review.
     */
    @Column(name = "RATING", nullable = false)
    private int rating;

    /**
     * The date when the review was written. Only stores date (no time).
     */
    @Column(name = "DATE_")
    @Temporal(TemporalType.DATE)
    private Date date;

    /**
     * Creates an empty review
     */
    public Review() {
    }

    /**
     * Creates a new review with all information.
     *
     * @param shoe The shoe being reviewed
     * @param user The user writing the review
     * @param description The review text/comment
     * @param rating The rating (1-5 stars)
     * @param date When the review was written
     */
    public Review(Shoe shoe, User user, String description, int rating, Date date) {
        this.shoe = shoe;
        this.user = user;
        this.description = description;
        this.rating = rating;
        this.date = date;
    }

    /**
     * @return The review ID
     */
    public int getId() {
        return id;
    }

    /**
     * @return The shoe being reviewed
     */
    public Shoe getShoe() {
        return shoe;
    }

    /**
     * @return The user who wrote the review
     */
    public User getUser() {
        return user;
    }

    /**
     * @return The review text/comment
     */
    public String getDescription() {
        return description;
    }

    /**
     * @return The rating (1-5 stars)
     */
    public int getRating() {
        return rating;
    }

    /**
     * @return When the review was written
     */
    public Date getDate() {
        return date;
    }

    /**
     * @param id The new review ID
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @param shoe The new shoe for the review
     */
    public void setShoe(Shoe shoe) {
        this.shoe = shoe;
    }

    /**
     * @param user The new user for the review
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * @param description The new review text
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @param rating The new rating (1-5 stars)
     */
    public void setRating(int rating) {
        this.rating = rating;
    }

    /**
     * @param date The new date for the review
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * Returns a short string with review info.
     *
     * @return String with ID, username, and rating
     */
    @Override
    public String toString() {
        return "Review{id=" + id + ", user=" + (user != null ? user.getUsername() : "null") + ", rating=" + rating + "}";
    }
}
