/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.util.List;
import javax.persistence.*;

/**
 * Represents a shoe in the store. Contains all information about a shoe and can
 * be compared by price.
 */
@Entity
@Table(name = "SHOE")
public class Shoe implements Comparable<Shoe> {

    /**
     * The unique ID of the shoe. Auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    private int id;

    /**
     * All reviews written for this shoe. If shoe is deleted, reviews are also
     * deleted.
     */
    @OneToMany(
            mappedBy = "shoe",
            cascade = CascadeType.REMOVE,
            orphanRemoval = true
    )
    private List<Review> reviews;

    /**
     * All orders containing this shoe. If shoe is deleted, orders are also
     * deleted.
     */
    @OneToMany(
            mappedBy = "shoe",
            cascade = CascadeType.REMOVE,
            orphanRemoval = true
    )
    private List<Order> orders;

    /**
     * The price of the shoe in euros. This is required.
     */
    @Column(name = "PRICE", nullable = false)
    private double price;

    /**
     * The model name of the shoe. Maximum 30 characters. Required.
     */
    @Column(name = "MODEL", nullable = false, length = 30)
    private String model;

    /**
     * The size of the shoe (like 38, 42, etc.). Required.
     */
    @Column(name = "SIZE", nullable = false)
    private double size;

    /**
     * Whether the shoe is exclusive or not. Stored as 'TRUE' or 'FALSE'.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "EXCLUSIVE", columnDefinition = "ENUM('TRUE', 'FALSE')")
    private Exclusive exclusive;

    /**
     * The date when the shoe was manufactured. Only stores date (no time).
     */
    @Column(name = "MANUFACTER_DATE")
    @Temporal(TemporalType.DATE)
    private java.util.Date manufactorDate;

    /**
     * The color of the shoe. Maximum 20 characters. Required.
     */
    @Column(name = "COLOR", nullable = false, length = 20)
    private String color;

    /**
     * The country where the shoe was made. Maximum 20 characters. Required.
     */
    @Column(name = "ORIGIN", nullable = false, length = 20)
    private String origin;

    /**
     * The brand of the shoe (Nike, Adidas, etc.). Maximum 20 characters.
     * Required.
     */
    @Column(name = "BRAND", nullable = false, length = 20)
    private String brand;

    /**
     * Whether the shoe is reserved or not. Stored as 'TRUE' or 'FALSE'.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "RESERVED", columnDefinition = "ENUM('TRUE', 'FALSE')")
    private Reserved reserved;

    /**
     * How many pairs of this shoe are available in stock.
     */
    @Column(name = "STOCK")
    private int stock;

    /**
     * The file path to the shoe's image. Maximum 100 characters. Required.
     */
    @Column(name = "IMGPATH", nullable = false, length = 100)
    private String path;

    /**
     * Creates an empty shoe with default values.
     */
    public Shoe() {
    }

    /**
     * Creates a new shoe with all details.
     *
     * @param price Price in euros
     * @param model Model name
     * @param size Shoe size
     * @param exclusive Exclusive status (TRUE/FALSE)
     * @param manufactorDate Manufacturing date
     * @param color Shoe color
     * @param origin Country of origin
     * @param brand Brand name
     * @param reserved Reservation status (TRUE/FALSE)
     * @param stock Available quantity
     * @param path Image file path
     */
    public Shoe(double price, String model, double size, Exclusive exclusive,
            java.util.Date manufactorDate, String color, String origin,
            String brand, Reserved reserved, int stock, String path) {
        this.price = price;
        this.model = model;
        this.size = size;
        this.exclusive = exclusive;
        this.manufactorDate = manufactorDate;
        this.color = color;
        this.origin = origin;
        this.brand = brand;
        this.reserved = reserved;
        this.stock = stock;
        this.path = path;
    }

    /**
     * Creates a shoe with basic information (for simple display).
     *
     * @param id Shoe ID
     * @param price Price in euros
     * @param model Model name
     * @param brand Brand name
     * @param path Image file path
     */
    public Shoe(int id, double price, String model, String brand, String path) {
        this.id = id;
        this.price = price;
        this.model = model;
        this.brand = brand;
        this.path = path;
    }

    // GETTERS - simple documentation
    /**
     * @return The shoe ID
     */
    public int getId() {
        return id;
    }

    /**
     * @return The shoe price in euros
     */
    public double getPrice() {
        return price;
    }

    /**
     * @return The model name
     */
    public String getModel() {
        return model;
    }

    /**
     * @return The shoe size
     */
    public double getSize() {
        return size;
    }

    /**
     * @return Exclusive status (TRUE/FALSE)
     */
    public Exclusive getExclusive() {
        return exclusive;
    }

    /**
     * @return Manufacturing date
     */
    public java.util.Date getManufactorDate() {
        return manufactorDate;
    }

    /**
     * @return The shoe color
     */
    public String getColor() {
        return color;
    }

    /**
     * @return Country of origin
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * @return The brand name
     */
    public String getBrand() {
        return brand;
    }

    /**
     * @return Reservation status (TRUE/FALSE)
     */
    public Reserved getReserved() {
        return reserved;
    }

    /**
     * @return Available stock quantity
     */
    public int getStock() {
        return stock;
    }

    /**
     * @return Image file path
     */
    public String getImgPath() {
        return path;
    }

    // SETTERS - simple documentation
    /**
     * @param id The new shoe ID
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @param price The new price in euros
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * @param model The new model name
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * @param size The new shoe size
     */
    public void setSize(double size) {
        this.size = size;
    }

    /**
     * @param exclusive The new exclusive status
     */
    public void setExclusive(Exclusive exclusive) {
        this.exclusive = exclusive;
    }

    /**
     * @param manufactorDate The new manufacturing date
     */
    public void setManufactorDate(java.util.Date manufactorDate) {
        this.manufactorDate = manufactorDate;
    }

    /**
     * @param color The new shoe color
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * @param origin The new country of origin
     */
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    /**
     * @param brand The new brand name
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * @param reserved The new reservation status
     */
    public void setReserved(Reserved reserved) {
        this.reserved = reserved;
    }

    /**
     * @param stock The new stock quantity
     */
    public void setStock(int stock) {
        this.stock = stock;
    }

    /**
     * @param path The new image file path
     */
    public void setImgPath(String path) {
        this.path = path;
    }

    /**
     * Returns a short string with shoe information.
     *
     * @return String with ID, model, brand, and price
     */
    @Override
    public String toString() {
        return "Shoe{id=" + id + ", model=" + model + ", brand=" + brand + ", price=" + price + "}";
    }

    /**
     * Compares this shoe with another shoe by price. Used for sorting shoes
     * from cheapest to most expensive.
     *
     * @param otro The other shoe to compare with
     * @return Negative if this is cheaper, positive if more expensive, 0 if
     * same price
     */
    @Override
    public int compareTo(Shoe otro) {
        return Double.compare(this.price, otro.price);
    }
}
